/*
 Generated by typeshare 1.13.3
*/

export interface ConfigUpdateResultTs {
	message: string;
}

export interface EgsInfoTs {
	erogamescape_id: number;
	gamename: string;
	gamename_ruby: string;
	brandname: string;
	brandname_ruby: string;
	sellday: string;
	is_nukige: boolean;
}

export interface DlsiteGameTs {
	id: string;
	category: string;
	title: string;
	image_url: string;
	egs_info?: EgsInfoTs;
}

export interface DlsiteSyncGamesRequestTs {
	games: DlsiteGameTs[];
	extension_id: string;
}

export interface DmmPackKeyTs {
	store_id: string;
	category: string;
	subcategory: string;
}

export interface DmmGameTs {
	id: string;
	category: string;
	subcategory: string;
	title: string;
	image_url: string;
	egs_info?: EgsInfoTs;
	parent_pack?: DmmPackKeyTs;
}

export interface DmmSyncGamesRequestTs {
	games: DmmGameTs[];
	extension_id: string;
}

export interface DownloadCompletedTs {
	id: number;
	filename: string;
	mime?: string;
	url?: string;
	start_time?: string;
	end_time?: string;
}

export type DownloadIntentTs = 
	| { case: "Dmm", value: {
	game_store_id: string;
	game_category: string;
	game_subcategory: string;
	parent_pack_store_id?: string;
	parent_pack_category?: string;
	parent_pack_subcategory?: string;
}}
	| { case: "Dlsite", value: {
	game_store_id: string;
	game_category: string;
}};

export interface DownloadsCompletedRequestTs {
	extension_id: string;
	items: DownloadCompletedTs[];
	intent: DownloadIntentTs;
}

export interface ExtensionConfigTs {
	auto_sync: boolean;
	allowed_domains: string[];
	sync_interval_minutes: number;
	debug_mode: boolean;
}

export interface GetStatusRequestTs {
}

export interface HealthCheckRequestTs {
}

export interface HealthCheckResultTs {
	message: string;
	version: string;
}

export type NativeMessageCase = 
	| { case: "SyncDmmGames", value: DmmSyncGamesRequestTs }
	| { case: "SyncDlsiteGames", value: DlsiteSyncGamesRequestTs }
	| { case: "DownloadsCompleted", value: DownloadsCompletedRequestTs }
	| { case: "GetStatus", value: GetStatusRequestTs }
	| { case: "SetConfig", value: ExtensionConfigTs }
	| { case: "HealthCheck", value: HealthCheckRequestTs };

export interface NativeMessageTs {
	request_id: string;
	message: NativeMessageCase;
}

export type NativeResponseCase = 
	| { case: "SyncGamesResult", value: SyncBatchResultTs }
	| { case: "StatusResult", value: SyncStatusTs }
	| { case: "ConfigResult", value: ConfigUpdateResultTs }
	| { case: "HealthCheckResult", value: HealthCheckResultTs };

export interface NativeResponseTs {
	success: boolean;
	error: string;
	request_id: string;
	response?: NativeResponseCase;
}

export interface SyncBatchResultTs {
	success_count: number;
	new_count: number;
	error_count: number;
	errors: string[];
	synced_games: string[];
}

export interface TimestampTs {
	seconds: number;
	nanos: number;
}

export interface SyncStatusTs {
	last_sync?: TimestampTs;
	total_synced: number;
	connected_extensions: number;
	is_running: boolean;
	connection_status: string;
	error_message: string;
}

