// @generated by protoc-gen-es v2.0.0 with parameter "target=ts,import_extension=none"
// @generated from file extension_internal/packs.proto (package launcherg.extension_internal.packs, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file extension_internal/packs.proto.
 */
export const file_extension_internal_packs: GenFile = /*@__PURE__*/
  fileDesc("Ch5leHRlbnNpb25faW50ZXJuYWwvcGFja3MucHJvdG8SImxhdW5jaGVyZy5leHRlbnNpb25faW50ZXJuYWwucGFja3MiFgoUR2V0RG1tUGFja0lkc1JlcXVlc3QiKgoVR2V0RG1tUGFja0lkc1Jlc3BvbnNlEhEKCXN0b3JlX2lkcxgBIAMoCULaAQomY29tLmxhdW5jaGVyZy5leHRlbnNpb25faW50ZXJuYWwucGFja3NCClBhY2tzUHJvdG9QAaICA0xFUKoCIUxhdW5jaGVyZy5FeHRlbnNpb25JbnRlcm5hbC5QYWNrc8oCIUxhdW5jaGVyZ1xFeHRlbnNpb25JbnRlcm5hbFxQYWNrc+ICLUxhdW5jaGVyZ1xFeHRlbnNpb25JbnRlcm5hbFxQYWNrc1xHUEJNZXRhZGF0YeoCI0xhdW5jaGVyZzo6RXh0ZW5zaW9uSW50ZXJuYWw6OlBhY2tzYgZwcm90bzM");

/**
 * @generated from message launcherg.extension_internal.packs.GetDmmPackIdsRequest
 */
export type GetDmmPackIdsRequest = Message<"launcherg.extension_internal.packs.GetDmmPackIdsRequest"> & {
};

/**
 * Describes the message launcherg.extension_internal.packs.GetDmmPackIdsRequest.
 * Use `create(GetDmmPackIdsRequestSchema)` to create a new message.
 */
export const GetDmmPackIdsRequestSchema: GenMessage<GetDmmPackIdsRequest> = /*@__PURE__*/
  messageDesc(file_extension_internal_packs, 0);

/**
 * @generated from message launcherg.extension_internal.packs.GetDmmPackIdsResponse
 */
export type GetDmmPackIdsResponse = Message<"launcherg.extension_internal.packs.GetDmmPackIdsResponse"> & {
  /**
   * @generated from field: repeated string store_ids = 1;
   */
  storeIds: string[];
};

/**
 * Describes the message launcherg.extension_internal.packs.GetDmmPackIdsResponse.
 * Use `create(GetDmmPackIdsResponseSchema)` to create a new message.
 */
export const GetDmmPackIdsResponseSchema: GenMessage<GetDmmPackIdsResponse> = /*@__PURE__*/
  messageDesc(file_extension_internal_packs, 1);

