// @generated by protoc-gen-es v2.0.0 with parameter "target=ts,import_extension=none"
// @generated from file native_messaging/sync.proto (package launcherg.sync, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file native_messaging/sync.proto.
 */
export const file_native_messaging_sync: GenFile = /*@__PURE__*/
  fileDesc("ChtuYXRpdmVfbWVzc2FnaW5nL3N5bmMucHJvdG8SDmxhdW5jaGVyZy5zeW5jImkKEFN5bmNHYW1lc1JlcXVlc3QSDQoFc3RvcmUYASABKAkSMAoFZ2FtZXMYAiADKAsyIS5sYXVuY2hlcmcuc3luYy5FeHRyYWN0ZWRHYW1lRGF0YRIUCgxleHRlbnNpb25faWQYAyABKAki/wEKEUV4dHJhY3RlZEdhbWVEYXRhEhAKCHN0b3JlX2lkGAEgASgJEg0KBXRpdGxlGAIgASgJEhQKDHB1cmNoYXNlX3VybBgDIAEoCRIVCg1wdXJjaGFzZV9kYXRlGAQgASgJEhUKDXRodW1ibmFpbF91cmwYBSABKAkSTgoPYWRkaXRpb25hbF9kYXRhGAYgAygLMjUubGF1bmNoZXJnLnN5bmMuRXh0cmFjdGVkR2FtZURhdGEuQWRkaXRpb25hbERhdGFFbnRyeRo1ChNBZGRpdGlvbmFsRGF0YUVudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEiYwoPU3luY0JhdGNoUmVzdWx0EhUKDXN1Y2Nlc3NfY291bnQYASABKA0SEwoLZXJyb3JfY291bnQYAiABKA0SDgoGZXJyb3JzGAMgAygJEhQKDHN5bmNlZF9nYW1lcxgEIAMoCUJ4ChJjb20ubGF1bmNoZXJnLnN5bmNCCVN5bmNQcm90b1ABogIDTFNYqgIOTGF1bmNoZXJnLlN5bmPKAg5MYXVuY2hlcmdcU3luY+ICGkxhdW5jaGVyZ1xTeW5jXEdQQk1ldGFkYXRh6gIPTGF1bmNoZXJnOjpTeW5jYgZwcm90bzM");

/**
 * ゲーム同期リクエスト
 *
 * @generated from message launcherg.sync.SyncGamesRequest
 */
export type SyncGamesRequest = Message<"launcherg.sync.SyncGamesRequest"> & {
  /**
   * "DMM" | "DLSite"
   *
   * @generated from field: string store = 1;
   */
  store: string;

  /**
   * @generated from field: repeated launcherg.sync.ExtractedGameData games = 2;
   */
  games: ExtractedGameData[];

  /**
   * @generated from field: string extension_id = 3;
   */
  extensionId: string;
};

/**
 * Describes the message launcherg.sync.SyncGamesRequest.
 * Use `create(SyncGamesRequestSchema)` to create a new message.
 */
export const SyncGamesRequestSchema: GenMessage<SyncGamesRequest> = /*@__PURE__*/
  messageDesc(file_native_messaging_sync, 0);

/**
 * 抽出されたゲームデータ
 *
 * @generated from message launcherg.sync.ExtractedGameData
 */
export type ExtractedGameData = Message<"launcherg.sync.ExtractedGameData"> & {
  /**
   * @generated from field: string store_id = 1;
   */
  storeId: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string purchase_url = 3;
   */
  purchaseUrl: string;

  /**
   * optional
   *
   * @generated from field: string purchase_date = 4;
   */
  purchaseDate: string;

  /**
   * optional
   *
   * @generated from field: string thumbnail_url = 5;
   */
  thumbnailUrl: string;

  /**
   * @generated from field: map<string, string> additional_data = 6;
   */
  additionalData: { [key: string]: string };
};

/**
 * Describes the message launcherg.sync.ExtractedGameData.
 * Use `create(ExtractedGameDataSchema)` to create a new message.
 */
export const ExtractedGameDataSchema: GenMessage<ExtractedGameData> = /*@__PURE__*/
  messageDesc(file_native_messaging_sync, 1);

/**
 * ゲーム同期結果のバッチレスポンス
 *
 * @generated from message launcherg.sync.SyncBatchResult
 */
export type SyncBatchResult = Message<"launcherg.sync.SyncBatchResult"> & {
  /**
   * @generated from field: uint32 success_count = 1;
   */
  successCount: number;

  /**
   * @generated from field: uint32 error_count = 2;
   */
  errorCount: number;

  /**
   * @generated from field: repeated string errors = 3;
   */
  errors: string[];

  /**
   * ゲームタイトルのリスト
   *
   * @generated from field: repeated string synced_games = 4;
   */
  syncedGames: string[];
};

/**
 * Describes the message launcherg.sync.SyncBatchResult.
 * Use `create(SyncBatchResultSchema)` to create a new message.
 */
export const SyncBatchResultSchema: GenMessage<SyncBatchResult> = /*@__PURE__*/
  messageDesc(file_native_messaging_sync, 2);

