// @generated by protoc-gen-es v2.0.0 with parameter "target=ts,import_extension=none"
// @generated from file native_messaging/common.proto (package launcherg.common, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { DlsiteSyncGamesRequest, DmmSyncGamesRequest, SyncBatchResult } from "./sync_pb";
import { file_native_messaging_sync } from "./sync_pb";
import type { ExtensionConfig, SyncStatus } from "./status_pb";
import { file_native_messaging_status } from "./status_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file native_messaging/common.proto.
 */
export const file_native_messaging_common: GenFile = /*@__PURE__*/
  fileDesc("Ch1uYXRpdmVfbWVzc2FnaW5nL2NvbW1vbi5wcm90bxIQbGF1bmNoZXJnLmNvbW1vbiKSAwoNTmF0aXZlTWVzc2FnZRItCgl0aW1lc3RhbXAYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhIKCnJlcXVlc3RfaWQYAiABKAkSPQoOc3luY19kbW1fZ2FtZXMYCiABKAsyIy5sYXVuY2hlcmcuc3luYy5EbW1TeW5jR2FtZXNSZXF1ZXN0SAASQwoRc3luY19kbHNpdGVfZ2FtZXMYCyABKAsyJi5sYXVuY2hlcmcuc3luYy5EbHNpdGVTeW5jR2FtZXNSZXF1ZXN0SAASOAoKZ2V0X3N0YXR1cxgMIAEoCzIiLmxhdW5jaGVyZy5jb21tb24uR2V0U3RhdHVzUmVxdWVzdEgAEjcKCnNldF9jb25maWcYDSABKAsyIS5sYXVuY2hlcmcuc3RhdHVzLkV4dGVuc2lvbkNvbmZpZ0gAEjwKDGhlYWx0aF9jaGVjaxgOIAEoCzIkLmxhdW5jaGVyZy5jb21tb24uSGVhbHRoQ2hlY2tSZXF1ZXN0SABCCQoHbWVzc2FnZSISChBHZXRTdGF0dXNSZXF1ZXN0IhQKEkhlYWx0aENoZWNrUmVxdWVzdCLIAgoOTmF0aXZlUmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCBINCgVlcnJvchgCIAEoCRISCgpyZXF1ZXN0X2lkGAMgASgJEjwKEXN5bmNfZ2FtZXNfcmVzdWx0GAogASgLMh8ubGF1bmNoZXJnLnN5bmMuU3luY0JhdGNoUmVzdWx0SAASNQoNc3RhdHVzX3Jlc3VsdBgLIAEoCzIcLmxhdW5jaGVyZy5zdGF0dXMuU3luY1N0YXR1c0gAEj0KDWNvbmZpZ19yZXN1bHQYDCABKAsyJC5sYXVuY2hlcmcuY29tbW9uLkNvbmZpZ1VwZGF0ZVJlc3VsdEgAEkIKE2hlYWx0aF9jaGVja19yZXN1bHQYDSABKAsyIy5sYXVuY2hlcmcuY29tbW9uLkhlYWx0aENoZWNrUmVzdWx0SABCCgoIcmVzcG9uc2UiJQoSQ29uZmlnVXBkYXRlUmVzdWx0Eg8KB21lc3NhZ2UYASABKAkiNQoRSGVhbHRoQ2hlY2tSZXN1bHQSDwoHbWVzc2FnZRgBIAEoCRIPCgd2ZXJzaW9uGAIgASgJQoQBChRjb20ubGF1bmNoZXJnLmNvbW1vbkILQ29tbW9uUHJvdG9QAaICA0xDWKoCEExhdW5jaGVyZy5Db21tb27KAhBMYXVuY2hlcmdcQ29tbW9u4gIcTGF1bmNoZXJnXENvbW1vblxHUEJNZXRhZGF0YeoCEUxhdW5jaGVyZzo6Q29tbW9uYgZwcm90bzM", [file_google_protobuf_timestamp, file_native_messaging_sync, file_native_messaging_status]);

/**
 * Native Messaging Hostへのリクエストメッセージ
 *
 * @generated from message launcherg.common.NativeMessage
 */
export type NativeMessage = Message<"launcherg.common.NativeMessage"> & {
  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 1;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: string request_id = 2;
   */
  requestId: string;

  /**
   * oneofを使用してメッセージタイプとペイロードの整合性を保証
   *
   * @generated from oneof launcherg.common.NativeMessage.message
   */
  message: {
    /**
     * @generated from field: launcherg.sync.DmmSyncGamesRequest sync_dmm_games = 10;
     */
    value: DmmSyncGamesRequest;
    case: "syncDmmGames";
  } | {
    /**
     * @generated from field: launcherg.sync.DlsiteSyncGamesRequest sync_dlsite_games = 11;
     */
    value: DlsiteSyncGamesRequest;
    case: "syncDlsiteGames";
  } | {
    /**
     * @generated from field: launcherg.common.GetStatusRequest get_status = 12;
     */
    value: GetStatusRequest;
    case: "getStatus";
  } | {
    /**
     * @generated from field: launcherg.status.ExtensionConfig set_config = 13;
     */
    value: ExtensionConfig;
    case: "setConfig";
  } | {
    /**
     * @generated from field: launcherg.common.HealthCheckRequest health_check = 14;
     */
    value: HealthCheckRequest;
    case: "healthCheck";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message launcherg.common.NativeMessage.
 * Use `create(NativeMessageSchema)` to create a new message.
 */
export const NativeMessageSchema: GenMessage<NativeMessage> = /*@__PURE__*/
  messageDesc(file_native_messaging_common, 0);

/**
 * ステータス取得リクエスト（空のメッセージ）
 *
 * 空のメッセージ - リクエストパラメータは不要
 *
 * @generated from message launcherg.common.GetStatusRequest
 */
export type GetStatusRequest = Message<"launcherg.common.GetStatusRequest"> & {
};

/**
 * Describes the message launcherg.common.GetStatusRequest.
 * Use `create(GetStatusRequestSchema)` to create a new message.
 */
export const GetStatusRequestSchema: GenMessage<GetStatusRequest> = /*@__PURE__*/
  messageDesc(file_native_messaging_common, 1);

/**
 * ヘルスチェックリクエスト（空のメッセージ）
 *
 * 空のメッセージ - ping的な用途
 *
 * @generated from message launcherg.common.HealthCheckRequest
 */
export type HealthCheckRequest = Message<"launcherg.common.HealthCheckRequest"> & {
};

/**
 * Describes the message launcherg.common.HealthCheckRequest.
 * Use `create(HealthCheckRequestSchema)` to create a new message.
 */
export const HealthCheckRequestSchema: GenMessage<HealthCheckRequest> = /*@__PURE__*/
  messageDesc(file_native_messaging_common, 2);

/**
 * Native Messaging Hostからのレスポンスメッセージ
 *
 * @generated from message launcherg.common.NativeResponse
 */
export type NativeResponse = Message<"launcherg.common.NativeResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: string error = 2;
   */
  error: string;

  /**
   * @generated from field: string request_id = 3;
   */
  requestId: string;

  /**
   * oneofを使用してレスポンスタイプとデータの整合性を保証
   *
   * @generated from oneof launcherg.common.NativeResponse.response
   */
  response: {
    /**
     * @generated from field: launcherg.sync.SyncBatchResult sync_games_result = 10;
     */
    value: SyncBatchResult;
    case: "syncGamesResult";
  } | {
    /**
     * @generated from field: launcherg.status.SyncStatus status_result = 11;
     */
    value: SyncStatus;
    case: "statusResult";
  } | {
    /**
     * @generated from field: launcherg.common.ConfigUpdateResult config_result = 12;
     */
    value: ConfigUpdateResult;
    case: "configResult";
  } | {
    /**
     * @generated from field: launcherg.common.HealthCheckResult health_check_result = 13;
     */
    value: HealthCheckResult;
    case: "healthCheckResult";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message launcherg.common.NativeResponse.
 * Use `create(NativeResponseSchema)` to create a new message.
 */
export const NativeResponseSchema: GenMessage<NativeResponse> = /*@__PURE__*/
  messageDesc(file_native_messaging_common, 3);

/**
 * 設定更新結果
 *
 * @generated from message launcherg.common.ConfigUpdateResult
 */
export type ConfigUpdateResult = Message<"launcherg.common.ConfigUpdateResult"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message launcherg.common.ConfigUpdateResult.
 * Use `create(ConfigUpdateResultSchema)` to create a new message.
 */
export const ConfigUpdateResultSchema: GenMessage<ConfigUpdateResult> = /*@__PURE__*/
  messageDesc(file_native_messaging_common, 4);

/**
 * ヘルスチェック結果
 *
 * @generated from message launcherg.common.HealthCheckResult
 */
export type HealthCheckResult = Message<"launcherg.common.HealthCheckResult"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * @generated from field: string version = 2;
   */
  version: string;
};

/**
 * Describes the message launcherg.common.HealthCheckResult.
 * Use `create(HealthCheckResultSchema)` to create a new message.
 */
export const HealthCheckResultSchema: GenMessage<HealthCheckResult> = /*@__PURE__*/
  messageDesc(file_native_messaging_common, 5);

