// @generated by protoc-gen-es v2.0.0 with parameter "target=ts,import_extension=none"
// @generated from file native_messaging/packs.proto (package launcherg.packs, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file native_messaging/packs.proto.
 */
export const file_native_messaging_packs: GenFile = /*@__PURE__*/
  fileDesc("ChxuYXRpdmVfbWVzc2FnaW5nL3BhY2tzLnByb3RvEg9sYXVuY2hlcmcucGFja3MiLAoUR2V0RG1tUGFja0lkc1JlcXVlc3QSFAoMZXh0ZW5zaW9uX2lkGAEgASgJIicKEkRtbVBhY2tJZHNSZXNwb25zZRIRCglzdG9yZV9pZHMYASADKAlCfgoTY29tLmxhdW5jaGVyZy5wYWNrc0IKUGFja3NQcm90b1ABogIDTFBYqgIPTGF1bmNoZXJnLlBhY2tzygIPTGF1bmNoZXJnXFBhY2tz4gIbTGF1bmNoZXJnXFBhY2tzXEdQQk1ldGFkYXRh6gIQTGF1bmNoZXJnOjpQYWNrc2IGcHJvdG8z");

/**
 * @generated from message launcherg.packs.GetDmmPackIdsRequest
 */
export type GetDmmPackIdsRequest = Message<"launcherg.packs.GetDmmPackIdsRequest"> & {
  /**
   * @generated from field: string extension_id = 1;
   */
  extensionId: string;
};

/**
 * Describes the message launcherg.packs.GetDmmPackIdsRequest.
 * Use `create(GetDmmPackIdsRequestSchema)` to create a new message.
 */
export const GetDmmPackIdsRequestSchema: GenMessage<GetDmmPackIdsRequest> = /*@__PURE__*/
  messageDesc(file_native_messaging_packs, 0);

/**
 * @generated from message launcherg.packs.DmmPackIdsResponse
 */
export type DmmPackIdsResponse = Message<"launcherg.packs.DmmPackIdsResponse"> & {
  /**
   * @generated from field: repeated string store_ids = 1;
   */
  storeIds: string[];
};

/**
 * Describes the message launcherg.packs.DmmPackIdsResponse.
 * Use `create(DmmPackIdsResponseSchema)` to create a new message.
 */
export const DmmPackIdsResponseSchema: GenMessage<DmmPackIdsResponse> = /*@__PURE__*/
  messageDesc(file_native_messaging_packs, 1);

