// @generated by protoc-gen-es v2.0.0 with parameter "target=ts,import_extension=none"
// @generated from file native_messaging/status.proto (package launcherg.status, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file native_messaging/status.proto.
 */
export const file_native_messaging_status: GenFile = /*@__PURE__*/
  fileDesc("Ch1uYXRpdmVfbWVzc2FnaW5nL3N0YXR1cy5wcm90bxIQbGF1bmNoZXJnLnN0YXR1cyLiAQoKU3luY1N0YXR1cxItCglsYXN0X3N5bmMYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhQKDHRvdGFsX3N5bmNlZBgCIAEoDRIcChRjb25uZWN0ZWRfZXh0ZW5zaW9ucxgDIAMoCRISCgppc19ydW5uaW5nGAQgASgIEkYKEWNvbm5lY3Rpb25fc3RhdHVzGAUgASgOMisubGF1bmNoZXJnLnN0YXR1cy5FeHRlbnNpb25Db25uZWN0aW9uU3RhdHVzEhUKDWVycm9yX21lc3NhZ2UYBiABKAkicAoPRXh0ZW5zaW9uQ29uZmlnEhEKCWF1dG9fc3luYxgBIAEoCBIXCg9hbGxvd2VkX2RvbWFpbnMYAiADKAkSHQoVc3luY19pbnRlcnZhbF9taW51dGVzGAMgASgNEhIKCmRlYnVnX21vZGUYBCABKAgqjgQKGUV4dGVuc2lvbkNvbm5lY3Rpb25TdGF0dXMSKwonRVhURU5TSU9OX0NPTk5FQ1RJT05fU1RBVFVTX1VOU1BFQ0lGSUVEEAASKQolRVhURU5TSU9OX0NPTk5FQ1RJT05fU1RBVFVTX0NPTk5FQ1RFRBABEioKJkVYVEVOU0lPTl9DT05ORUNUSU9OX1NUQVRVU19DT05ORUNUSU5HEAISLgoqRVhURU5TSU9OX0NPTk5FQ1RJT05fU1RBVFVTX0hPU1RfTk9UX0ZPVU5EEAMSMwovRVhURU5TSU9OX0NPTk5FQ1RJT05fU1RBVFVTX0hPU1RfU1RBUlRVUF9GQUlMRUQQBBI0CjBFWFRFTlNJT05fQ09OTkVDVElPTl9TVEFUVVNfSEVBTFRIX0NIRUNLX1RJTUVPVVQQBRIzCi9FWFRFTlNJT05fQ09OTkVDVElPTl9TVEFUVVNfSEVBTFRIX0NIRUNLX0ZBSUxFRBAGEjMKL0VYVEVOU0lPTl9DT05ORUNUSU9OX1NUQVRVU19DT01NVU5JQ0FUSU9OX0VSUk9SEAcSOQo1RVhURU5TSU9OX0NPTk5FQ1RJT05fU1RBVFVTX1BST0NFU1NfVEVSTUlOQVRJT05fRVJST1IQCBItCilFWFRFTlNJT05fQ09OTkVDVElPTl9TVEFUVVNfVU5LTk9XTl9FUlJPUhAJQoQBChRjb20ubGF1bmNoZXJnLnN0YXR1c0ILU3RhdHVzUHJvdG9QAaICA0xTWKoCEExhdW5jaGVyZy5TdGF0dXPKAhBMYXVuY2hlcmdcU3RhdHVz4gIcTGF1bmNoZXJnXFN0YXR1c1xHUEJNZXRhZGF0YeoCEUxhdW5jaGVyZzo6U3RhdHVzYgZwcm90bzM", [file_google_protobuf_timestamp]);

/**
 * 同期ステータス情報
 *
 * @generated from message launcherg.status.SyncStatus
 */
export type SyncStatus = Message<"launcherg.status.SyncStatus"> & {
  /**
   * 最後の同期時刻（optional）
   *
   * @generated from field: google.protobuf.Timestamp last_sync = 1;
   */
  lastSync?: Timestamp;

  /**
   * 同期したゲーム総数
   *
   * @generated from field: uint32 total_synced = 2;
   */
  totalSynced: number;

  /**
   * 接続済み拡張機能のリスト
   *
   * @generated from field: repeated string connected_extensions = 3;
   */
  connectedExtensions: string[];

  /**
   * Native Messaging Hostが動作中かどうか
   *
   * @generated from field: bool is_running = 4;
   */
  isRunning: boolean;

  /**
   * 接続ステータス
   *
   * @generated from field: launcherg.status.ExtensionConnectionStatus connection_status = 5;
   */
  connectionStatus: ExtensionConnectionStatus;

  /**
   * エラーメッセージ（optional）
   *
   * @generated from field: string error_message = 6;
   */
  errorMessage: string;
};

/**
 * Describes the message launcherg.status.SyncStatus.
 * Use `create(SyncStatusSchema)` to create a new message.
 */
export const SyncStatusSchema: GenMessage<SyncStatus> = /*@__PURE__*/
  messageDesc(file_native_messaging_status, 0);

/**
 * 拡張機能の設定
 *
 * @generated from message launcherg.status.ExtensionConfig
 */
export type ExtensionConfig = Message<"launcherg.status.ExtensionConfig"> & {
  /**
   * 自動同期の有効・無効
   *
   * @generated from field: bool auto_sync = 1;
   */
  autoSync: boolean;

  /**
   * 許可されたドメインのリスト
   *
   * @generated from field: repeated string allowed_domains = 2;
   */
  allowedDomains: string[];

  /**
   * 同期間隔（分）
   *
   * @generated from field: uint32 sync_interval_minutes = 3;
   */
  syncIntervalMinutes: number;

  /**
   * デバッグモードの有効・無効
   *
   * @generated from field: bool debug_mode = 4;
   */
  debugMode: boolean;
};

/**
 * Describes the message launcherg.status.ExtensionConfig.
 * Use `create(ExtensionConfigSchema)` to create a new message.
 */
export const ExtensionConfigSchema: GenMessage<ExtensionConfig> = /*@__PURE__*/
  messageDesc(file_native_messaging_status, 1);

/**
 * 拡張機能の接続ステータス
 *
 * @generated from enum launcherg.status.ExtensionConnectionStatus
 */
export enum ExtensionConnectionStatus {
  /**
   * @generated from enum value: EXTENSION_CONNECTION_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * 正常に接続済み
   *
   * @generated from enum value: EXTENSION_CONNECTION_STATUS_CONNECTED = 1;
   */
  CONNECTED = 1,

  /**
   * 接続中（チェック実行中）
   *
   * @generated from enum value: EXTENSION_CONNECTION_STATUS_CONNECTING = 2;
   */
  CONNECTING = 2,

  /**
   * Native Messaging Hostの実行ファイルが見つからない
   *
   * @generated from enum value: EXTENSION_CONNECTION_STATUS_HOST_NOT_FOUND = 3;
   */
  HOST_NOT_FOUND = 3,

  /**
   * Native Messaging Hostプロセスの起動に失敗
   *
   * @generated from enum value: EXTENSION_CONNECTION_STATUS_HOST_STARTUP_FAILED = 4;
   */
  HOST_STARTUP_FAILED = 4,

  /**
   * ヘルスチェック通信のタイムアウト
   *
   * @generated from enum value: EXTENSION_CONNECTION_STATUS_HEALTH_CHECK_TIMEOUT = 5;
   */
  HEALTH_CHECK_TIMEOUT = 5,

  /**
   * ヘルスチェック通信でエラーレスポンス
   *
   * @generated from enum value: EXTENSION_CONNECTION_STATUS_HEALTH_CHECK_FAILED = 6;
   */
  HEALTH_CHECK_FAILED = 6,

  /**
   * JSON解析エラーなどの通信エラー
   *
   * @generated from enum value: EXTENSION_CONNECTION_STATUS_COMMUNICATION_ERROR = 7;
   */
  COMMUNICATION_ERROR = 7,

  /**
   * プロセス終了時のエラー
   *
   * @generated from enum value: EXTENSION_CONNECTION_STATUS_PROCESS_TERMINATION_ERROR = 8;
   */
  PROCESS_TERMINATION_ERROR = 8,

  /**
   * 不明なエラー
   *
   * @generated from enum value: EXTENSION_CONNECTION_STATUS_UNKNOWN_ERROR = 9;
   */
  UNKNOWN_ERROR = 9,
}

/**
 * Describes the enum launcherg.status.ExtensionConnectionStatus.
 */
export const ExtensionConnectionStatusSchema: GenEnum<ExtensionConnectionStatus> = /*@__PURE__*/
  enumDesc(file_native_messaging_status, 0);

