// @generated by protoc-gen-es v2.0.0 with parameter "target=ts,import_extension=none"
// @generated from file native_messaging/sync.proto (package launcherg.sync, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file native_messaging/sync.proto.
 */
export const file_native_messaging_sync: GenFile = /*@__PURE__*/
  fileDesc("ChtuYXRpdmVfbWVzc2FnaW5nL3N5bmMucHJvdG8SDmxhdW5jaGVyZy5zeW5jIlMKE0RtbVN5bmNHYW1lc1JlcXVlc3QSJgoFZ2FtZXMYASADKAsyFy5sYXVuY2hlcmcuc3luYy5EbW1HYW1lEhQKDGV4dGVuc2lvbl9pZBgCIAEoCSJZChZEbHNpdGVTeW5jR2FtZXNSZXF1ZXN0EikKBWdhbWVzGAEgAygLMhoubGF1bmNoZXJnLnN5bmMuRGxzaXRlR2FtZRIUCgxleHRlbnNpb25faWQYAiABKAkiPAoHRG1tR2FtZRIKCgJpZBgBIAEoCRIQCghjYXRlZ29yeRgCIAEoCRITCgtzdWJjYXRlZ29yeRgDIAEoCSIqCgpEbHNpdGVHYW1lEgoKAmlkGAEgASgJEhAKCGNhdGVnb3J5GAIgASgJImMKD1N5bmNCYXRjaFJlc3VsdBIVCg1zdWNjZXNzX2NvdW50GAEgASgNEhMKC2Vycm9yX2NvdW50GAIgASgNEg4KBmVycm9ycxgDIAMoCRIUCgxzeW5jZWRfZ2FtZXMYBCADKAlCeAoSY29tLmxhdW5jaGVyZy5zeW5jQglTeW5jUHJvdG9QAaICA0xTWKoCDkxhdW5jaGVyZy5TeW5jygIOTGF1bmNoZXJnXFN5bmPiAhpMYXVuY2hlcmdcU3luY1xHUEJNZXRhZGF0YeoCD0xhdW5jaGVyZzo6U3luY2IGcHJvdG8z");

/**
 * DMM 向けゲーム同期リクエスト
 *
 * @generated from message launcherg.sync.DmmSyncGamesRequest
 */
export type DmmSyncGamesRequest = Message<"launcherg.sync.DmmSyncGamesRequest"> & {
  /**
   * @generated from field: repeated launcherg.sync.DmmGame games = 1;
   */
  games: DmmGame[];

  /**
   * @generated from field: string extension_id = 2;
   */
  extensionId: string;
};

/**
 * Describes the message launcherg.sync.DmmSyncGamesRequest.
 * Use `create(DmmSyncGamesRequestSchema)` to create a new message.
 */
export const DmmSyncGamesRequestSchema: GenMessage<DmmSyncGamesRequest> = /*@__PURE__*/
  messageDesc(file_native_messaging_sync, 0);

/**
 * DLsite 向けゲーム同期リクエスト
 *
 * @generated from message launcherg.sync.DlsiteSyncGamesRequest
 */
export type DlsiteSyncGamesRequest = Message<"launcherg.sync.DlsiteSyncGamesRequest"> & {
  /**
   * @generated from field: repeated launcherg.sync.DlsiteGame games = 1;
   */
  games: DlsiteGame[];

  /**
   * @generated from field: string extension_id = 2;
   */
  extensionId: string;
};

/**
 * Describes the message launcherg.sync.DlsiteSyncGamesRequest.
 * Use `create(DlsiteSyncGamesRequestSchema)` to create a new message.
 */
export const DlsiteSyncGamesRequestSchema: GenMessage<DlsiteSyncGamesRequest> = /*@__PURE__*/
  messageDesc(file_native_messaging_sync, 1);

/**
 * DMM のゲームデータ
 *
 * @generated from message launcherg.sync.DmmGame
 */
export type DmmGame = Message<"launcherg.sync.DmmGame"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * "mono" | "digital"
   *
   * @generated from field: string category = 2;
   */
  category: string;

  /**
   * "doujin" | "pcgame"
   *
   * @generated from field: string subcategory = 3;
   */
  subcategory: string;
};

/**
 * Describes the message launcherg.sync.DmmGame.
 * Use `create(DmmGameSchema)` to create a new message.
 */
export const DmmGameSchema: GenMessage<DmmGame> = /*@__PURE__*/
  messageDesc(file_native_messaging_sync, 2);

/**
 * DLsite のゲームデータ
 *
 * @generated from message launcherg.sync.DlsiteGame
 */
export type DlsiteGame = Message<"launcherg.sync.DlsiteGame"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * "ai" | "maniax" | "bl" | "home" | "appx" | "girls" | "pro" | "girls-pro" | "soft"
   *
   * @generated from field: string category = 2;
   */
  category: string;
};

/**
 * Describes the message launcherg.sync.DlsiteGame.
 * Use `create(DlsiteGameSchema)` to create a new message.
 */
export const DlsiteGameSchema: GenMessage<DlsiteGame> = /*@__PURE__*/
  messageDesc(file_native_messaging_sync, 3);

/**
 * ゲーム同期結果のバッチレスポンス
 *
 * @generated from message launcherg.sync.SyncBatchResult
 */
export type SyncBatchResult = Message<"launcherg.sync.SyncBatchResult"> & {
  /**
   * @generated from field: uint32 success_count = 1;
   */
  successCount: number;

  /**
   * @generated from field: uint32 error_count = 2;
   */
  errorCount: number;

  /**
   * @generated from field: repeated string errors = 3;
   */
  errors: string[];

  /**
   * ゲームタイトルのリスト
   *
   * @generated from field: repeated string synced_games = 4;
   */
  syncedGames: string[];
};

/**
 * Describes the message launcherg.sync.SyncBatchResult.
 * Use `create(SyncBatchResultSchema)` to create a new message.
 */
export const SyncBatchResultSchema: GenMessage<SyncBatchResult> = /*@__PURE__*/
  messageDesc(file_native_messaging_sync, 4);

