-- 作品単位の除外テーブル

CREATE TABLE IF NOT EXISTS work_omits (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    work_id INTEGER NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(work_id),
    FOREIGN KEY(work_id) REFERENCES works(id) ON DELETE CASCADE
);

